apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-east-1"
      auth:
        jwt:
          serviceAccountRef:
            name: kubernetes-service-account 
            namespace: external-secrets