# vault-secretstore.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-aws-iam
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"            # KV-v2 mount
      version: "v2"
      auth:
        iam:
          path: "aws"       # **NOT** "auth/aws"
          region: "us-east-1"
          vaultRole: "external-secrets"
          vaultAwsIamServerID: "$OIDC_ISSUER_URL"
