apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-aws-iam
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"            # KV-v2 mount
      version: "v2"
      auth:
        iam:
          path: "aws"       # AWS auth mount name (not auth/aws)
          region: "us-east-1"
          vaultRole: "external-secrets"
          vaultAwsIamServerID: "oidc.eks.us-east-1.amazonaws.com/id/E7FCD5F8416707138082CEE9AF9891D8"

