apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-aws-iam
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: database/creds
        property: username 
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database/creds
        property: password
